services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: opendominion-app
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - '.:/var/www/html'
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: '${DB_DATABASE:-opendominion}'
      DB_USERNAME: '${DB_USERNAME:-opendominion}'
      DB_PASSWORD: '${DB_PASSWORD:-secret}'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      start_period: 120s
      interval: 15s
      retries: 3
      timeout: 5s
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - opendominion

  mariadb:
    image: 'mariadb:10'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE:-opendominion}'
      MYSQL_USER: '${DB_USERNAME:-opendominion}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'opendominion-mariadb:/var/lib/mysql'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-uroot', '-p${DB_PASSWORD:-secret}']
      retries: 5
      interval: 5s
      timeout: 5s
    networks:
      - opendominion

networks:
  opendominion:
    driver: bridge

volumes:
  opendominion-mariadb:
    driver: local
