<?php

return [
    'formulae' => [
    ],
    'networth' => [
        'land' => 20,
        'building' => 5,
        'units' => [
            'spy' => 5,
            'wizard' => 5,
            'archmage' => 5,
        ],
    ],
    'newdominion' => [
        'prestige' => 250,
        'peasants' => 1300,
        'draftees' => 0,
        'draft_rate' => 10,
        'resources' => [
            'platinum' => 100000,
            'food' => 15000,
            'lumber' => 15000,
            'mana' => 0,
            'ore' => 0,
            'gems' => 1000,
            'tech' => 0,
            'boats' => 0,
        ],
        'military' => [
            'unit1' => 0,
            'unit2' => 150,
            'unit3' => 0,
            'unit4' => 0,
            'spies' => 25,
            'wizards' => 25,
            'archmages' => 0,
        ],
        'land' => [
            'plain' => 100,
            'mountain' => 20,
            'swamp' => 20,
            'cavern' => 20,
            'forest' => 40,
            'hill' => 20,
            'water' => 20,
        ],
        'home_land_extra' => 10,
        'buildings' => [
            'home' => 10,
            'alchemy' => 30,
            'farm' => 30,
            'smithy' => 0,
            'masonry' => 0,
            'ore_mine' => 0,
            'gryphon_nest' => 0,
            'tower' => 0,
            'wizard_guild' => 0,
            'temple' => 0,
            'diamond_mine' => 0,
            'school' => 0,
            'lumberyard' => 20,
            'forest_haven' => 0,
            'factory' => 0,
            'guard_tower' => 0,
            'shrine' => 0,
            'barracks' => 0,
            'dock' => 0,
        ],
    ],
    'types' => [
        'alignments' => [
            'good',
            'evil',
            'neutral',
            'other',
        ],
        'buildings' => [
            'home',
            'alchemy',
            'farm',
            'smithy',
            'masonry',
            'ore_mine',
            'gryphon_nest',
            'tower',
            'wizard_guild',
            'temple',
            'diamond_mine',
            'school',
            'lumberyard',
            'forest_haven',
            'factory',
            'guard_tower',
            'shrine',
            'barracks',
            'dock',
        ],
        'improvements' => [
            'science',
            'keep',
            'towers',
            'forges',
            'walls',
            'irrigation',
        ],
        'land' => [
            'plain',
            'mountain',
            'swamp',
            'cavern',
            'forest',
            'hill',
            'water',
        ],
        'resources' => [
            'platinum',
            'food',
            'lumber',
            'mana',
            'ore',
            'gems',
            'tech',
            'boats',
        ],
    ],
];
