name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    services:
      mariadb:
        image: mariadb:10.11
        env:
          MYSQL_DATABASE: opendominion
          MYSQL_USER: opendominion-user
          MYSQL_PASSWORD: opendominion-password
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10
    steps:
    - uses: actions/checkout@v6

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, pdo, pdo_mysql, xml, ctype, json, bcmath, curl
        coverage: none

    - name: Shut down MySQL server
      run: sudo service mysql stop

    - name: Install PHP dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Setup .env file
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: Create dummy mix-manifest.json file
      run: echo '{"/assets/app/css/app.css":"/dummy","/assets/app/js/app.js":"/dummy"}' > public/mix-manifest.json

    - name: Run database migrations
      run: php artisan migrate

    - name: Seed database
      run: php artisan db:seed

    - name: Sync game data
      run: php artisan game:data:sync

    - name: Run tests
      run: vendor/bin/phpunit
